baseURL = 'https://titus-briggs.github.io/'
languageCode = 'en-uk'
title = 'Titus Briggs'
theme = 'FixIt'

# ===== Direct html image sizing =====
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# ===== Click on images to zoom in =====
[params.page]
lightbox = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

# ===== About page =====
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 1
    pre = "<i class='fa-solid fa-circle-question'></i> "


# ===== Categories and tags =====
 [[menu.main]]
    identifier = "categories"
    parent = ""
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 2
    [menu.main.params]
      icon = "fa-solid fa-folder-tree"
  # [[menu.main]]
  #   identifier = "tags"
  #   parent = ""
  #   pre = ""
  #   post = ""
  #   name = "Tags"
  #   url = "/tags/"
  #   title = ""
  #   weight = 3
  #   [menu.main.params]
  #     icon = "fa-solid fa-tags"

# ===== Intro to site =====

[params.home.profile]
  enable = true
  title = "Work | Projects | Learning"
  subtitle = "A personal project for the work I do and the things I'm building on the side. Data work, tools, systems and whatever comes next. Part portfolio, part blog."
  typeit = true
  social = true
  disclaimer = ""

# ===== Contact me =====
[params.social]
  Linkedin = "https://www.linkedin.com/in/titus-briggs-1584b025a/"
  Email = "mailto:briggstitus@icloud.com"
  RSS = false


# ===== Colours =====
[params]
  colorScheme = "light"
  colorSchemeToggle = true


# ===== Date format =====
  dateFormat = "02/01/2006"


# ===== Google site verification =====

[params.verification]
google = "T8MjBXaAE0S__NMZrMqzleg5lVvkiQL6LrjMGPnbZeQ"

# ===== Umami Analytics =====

[params.analytics]
enable = true

[params.analytics.umami]
data_website_id = "5a9a7333-25a7-4efa-9d52-2c71531942d5"
src = "https://cloud.umami.is/script.js"


# ===== Test removing footer =====

  [params.footer]
    enable = true
    # whether to show copyright info
    copyright = false
    # whether to show the author
    author = true
    # Site creation year
    since = "2025"
    # FixIt 0.2.12 | NEW Public network security only in China (HTML format is supported)
    gov = ""
    # ICP info only in China (HTML format is supported)
    icp = ""
    # license info (HTML format is supported)
    license = ""
    # FixIt 0.3.0 | NEW whether to show Hugo and theme info
    [params.footer.powered]
      enable = false
      hugoLogo = false
      themeLogo = false
    # FixIt 0.2.17 | CHANGED Site creation time
    [params.footer.siteTime]
      enable = false
      animate = false
      icon = "fa-solid fa-heartbeat"
      pre = ""
      value = "" # e.g. "2021-12-18T16:15:22+08:00"
    # FixIt 0.2.17 | NEW footer lines order, optional values: ["first", 0, 1, 2, 3, 4, 5, "last"]
    [params.footer.order]
      powered = 0
      copyright = 0
      statistics = 0
      visitor = 0
      beian = 0

